name: Generate docs

on:
  push:
    branches: [main]

jobs:
  generate_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen texlive-latex texlive-collection-latexextra

      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/output/html
          publish_branch: gh-pages
